# -*- coding: utf-8 -*-
"""calisma5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dgjBv6bv20ngINT1k6BXhvAW223cwHbO
"""

a = 5
b = 10
# a = 10 b = 5 olsun
print(f"a nın ilk değeri : {a}" )
print(f"b nin  ilk değeri : {b}")

guls = a
a = b
b = guls
print(f"a nın değeri : {a}" )
print(f"b nin değeri : {b}")

a = 5
b = 10
# a = 10 b = 5 olsun
print(f"a nın ilk değeri : {a}" )
print(f"b nin  ilk değeri : {b}")

a, b = b, a  # daha kolay bir sekilde hallettik.

print(f"a nın değeri : {a}" )
print(f"b nin değeri : {b}")

name = "Gülsüm"
job = "teachers"
domain = "Cyber Security"
message = (                # buradaki parantez önemli kullanmayı unutma . parantez olanazsa örnek asağida
    f"Hi {name}."
    f"You are one of the {job} "
    f"in the {domain} section."
)
print(message)

name = "Gülsüm"
job = "teachers"
domain = "Cyber Security"
message = f"Hi {name}."\      # buarada parantez kullanmazsak o zaman messagenin yanından yazmaya başlar ve ters slash kullanırızz
    f"You are one of the {job} "\
    f"in the {domain} section."

print(message)

"""IMMUTABILITY

Mutable = Değiştirilebilir objeler => List, dict ve set.

Immutable = Değiştirilemez objeler => str,float,int,bool, tuple...
"""

name = "gülsüm"
print(name.upper())

name  # buarada tekrar name değişkenini çağırınca ilk tanımladığım sekliyle geliyor.

print(name)
name = name.capitalize()  # değiştirilmediği için içine yeni bir değer atadık.
print(name)

text = "porTakAl"
print(text.upper())
print(text.capitalize())
print(text.title())
print(text.swapcase())

name = "Selin"
"e" in name
"l" in name
"ç" not in name  # hep true

"E" in name.upper()  # bu sekilde true alabiliriz.

email = input("lütfen emailinizi giriniz:")
if "/" in email:
  print("yanlıs karakter girdiniz!")

email = "glsmesgi8@gmail.com"
email.startswith("gls")  # kelimenin en başından verilen str değeri ile başlayıp başlamadığına bakar.

email.endswith(".com")  # kelimenin en sonundan verilen str değeri ile bitip bitmediğine bakar.

email.startswith("glm")  # false çünkü en basından itibaren sıra nasılsa o sekilde sorulacak.

email.endswith("cm")  # aynı nedenden dolayı false

email.startswith("sm", 4, 9)  # 4. indeksle 9. indeks arası sm ile mi başlıyor diye sorduk false.

email.startswith("sm", 2, 5)  # true

text = "Olaylara bakış açınızı değiştirdiğinizde baktığınız şeyler de değişir."
print(text.endswith("değişir.", 15))
print(text.startswith("Olaylara", 0, 19))  # 0 ile 19 arası indekste mi başlıyor? true

text.count("i")  # metin içinde kaç tane i harfi var.

# cümledeki kelime sayısını öğrenmek için bosluk sayısı + 1 yaparız.
sentence = "mutsuzluğun en büyük sebebi fazla düşünmektir."
print(sentence.count(" ") + 1)

text = "geçmiş için ağlama."
text.index("ş")  # içerisinde bu değer yoksa hata alırım.

text = "anı yaşa ve güzelleştir."
text.index("zel")  # burada z harfinin indeksini verir.

text = "her zaman neyin yanlıs gidebileceğini düşünüyosan doğru gidebilecek her şeyi kaçırırısın."
# find() girilen metnin indeksini verir ancak değer yoksa -1 return eder.
print(text.find("z"))
print(text.find("v"))
print(len(text))  # karakter sayısı

# replace(old, new) eskiyi yeniyle değiştirme
text.replace("i", "*")  # i harfi olan her yere * koyduk

metin = "çilek çilek çilek"
metin.replace("çilek", "karpuz")

metin = "çilek çilek çilek"
metin.replace("çilek", "karpuz", 2)  # 2 tanesini değiştir.

# sadece ortada ki çileği karpuz yapmak istersem
metin = "çilek çilek çilek"
print(metin.replace("çilek", "karpuz", 2))
print(metin[:5] + metin[11:].replace("çilek", "karpuz") + metin[11:] )

text.swapcase()  # büyük harfi küçük, küçük harfi büyük yapar.

text.capitalize()  # ilk harf büyük diğerleri küçük.

text.upper()  # hepsi büyük

text.lower()  # hepsi küçük

text.title()  # bütün kelimelerin ilk harfleri büyük.

name = input("Lütfen isminizi giriniz:").upper().capitalize()
name.upper().capitalize() == "gülsüm"

text = "            python öğreniyorum                  "
print(text.strip())  # boşlukları temizler. rstrip dersem sağındaki, lstrip dersem solundaki boşlukları siler.

user_name = input("Please enter your user name:")

print(user_name.strip() == "glsm_15")

string = "dersimizdeyiz"
string.strip("z")  # basta veya sonda z harfi varsa siler.

metin = "çalşmadayız"
print(metin.strip("çaız"))  # basında veya sonunda bu harfler varsa siler.
print(metin.strip("açy"))  # sıra sıra bakıyo varsa siler yoksa durur.



