# -*- coding: utf-8 -*-
"""calisma2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLxbIKivGcEiohtoE62vVCu7YvhvY5wu
"""

print("python programming")

x = 8
print(x)

planet = "jubyter"
pi = 3.14
note = 100
print(planet, pi, note)

my_note = 100
your_note = 90
my_note = your_note
print(my_note)

x = y = z = "Gülsüm"
print(x)
print(y)
print(z)

january = march = may = july = august = october = december = 31
april = june = september = november = 30
february = 28
print(january, february, march, april, may, june, july, august, september, october, november, december)

thomas = 28
marry = 33
walter = None  # bilinmiyorsa none yazarız.
isabella = 40

website = "google.com"
website = "foor.com"
print(website)  # her zaman en son atanan değer okunur.

x = 15
y = 33
z = x
x = y
print(x)   # y , x e atandı 33 oldu
print(y)   # y aynı kaldı 33
print(z)   # x, z ye atandı ve 15 oldu

a, b, c = 5, 3.2, "hello"
print(a)
print(b)
print(c)  # sırayla değişekenlere atanacak.

name = "gülsüm"
print(type(name))

name = True
print(type(name))

name = 67
print(type(name))  # veri tipini return eder.









