# -*- coding: utf-8 -*-
"""calisma4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RCbwmMWMoKl2GvjVc5kYQzlTKqLeXtUL
"""

print(bool())  # False

print(bool(" "))  # True

[0] and 25  # False olamdığı için son true degerini return eder.25

{} or [] or ()  # True olmadığı için son false degerini return eder.()

print(2 and "hello")  # hello
print([] and "happy")  # []
print(None and ())  # None

print(2 or "hello")  # 2
print([] or "gülsüm")  # gülsüm
print(None or ())  # ()
print({} or 0)  # 0
print({0} or False)  # {0}

# KADAYIF DOLMASI YAPIMI

"""* Kadayıf (zorunlu)
* iç malzeme (zorunlu)
    * ceviz(isteğe bağlı)
    * fındık (isteğe bağlı)
    * fıstık (isteğe bağlı)
* şerbet(zorunlu)
    * şeker
    * su
* yumurta(zorunlu)
"""

# kadayıf zorunlu
kadayif = True
# iç malzeme(en az bir zorunlu)
ceviz = True
findik = False
fistik = False
# serbet
su = True
seker = True
# yumurta zorunlu
yumurta = True
kadayif_dolmasi = kadayif and (ceviz or findik or fistik) and (su and seker) and yumurta and "Afiyet olsun!"
kadayif_dolmasi

fruit = "strawberry"
print("dünya               :", fruit)
print("first letter        :", fruit[0])
print("second letter       :", fruit[1])
print("3rd to 5th letters  :", fruit[3:5])
print("letter all after 3rd:", fruit[3:])

city = "Tekirdağ"

print(city[2:5])
print(city[::1])
print(city[1:7:2])
print(city[::-1])
print(city[2::3])
print(city[1:1:-1])
print(city[-6:-2:3])
print(city[-5:-1:-1])

animal = "elephant"

print(animal[1:])
print(animal[:6])
print(animal[::2])
print(animal[1:5:2])
print(animal[::-1])

len(animal)

sayi = 1870  # bu sayı bütün haldedir elemanlarına tek tek ayrılamaz.
len(sayi)  # integer iterable değildir. hata verir.

sayi = 4567  # sayıyı tersten yazdır
sayi = int(str(sayi)[::-1])
print(sayi)
print(type(sayi))

vegetable = "patato"
print("patato kelimesinin uzunluğu   :", len(vegetable))

"gülsüm" + "eşgi"

"gülsüm" * 3

name = "gülsüm"
name += "eşgi"
name

str_one = "gülsüm"
str_two = "eşgi"
print(str_one + str_two)
print(3 * str_two)
print(* str_two)  # unpacking = 4 lü halde paket çikolatayı açıp tek tek ele almak gibi.
print(* str_two, sep = "-")

first = "güls"
first += "esgi"
print(first)
first += "28"
print(first)
first += "end"
print(first)

print("\U0001F600")  # unicode

# grinning face
print("\N{grinning face}")

name = input("lütfen isminizi giriniz:")
print("Merhaba {}. Size nasıl yardımcı olabiliriz?".format(name))

fruit = "apple"
vegetable = "cucumber"
amount = 8
print("The amount of {} we bought is {} pounds.".format(fruit, amount))

"ben sabah {} da uyandım. {}a gittim.".format(09.00, "bakkal")

"Yarın davet edildiğimiz yer {mekan}. Oraya gidip gitmeme konusunda {durum}ım. Neyse gitmeliyim {ihtimal}. ".format(mekan = "restorant", durum = "kararsız", ihtimal = "galiba")
#  keyword argument ile

"Herkes her şeyi çok {2} bidiğini zannediyor {0} kimse bir şey bilmiyor {1}".format( "ama", "gibi", "iyi")  # positional

isim = input("Lütfen adınızı giriniz:")
yas = input("Lütfen yaşınızı giriniz:")
print("Merhaba {1}! Yaşınız : {0}".format(yas, isim))  # positional

# keyword ve positional argument . önce positional argument yazılır sonra keyword argument gelir. yoksa hata alırız.
"Herkes her şeyi çok {1} bidiğini zannediyor {0} kimse bir şey bilmiyor {durum}".format( "ama", "iyi", durum= "gibi")







