# -*- coding: utf-8 -*-
"""çalışma1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sl-_8M14e27439-s115kGec8CieiupjE
"""

print("hello world")

print('gülsüm')

print("gülsümcüm ')
# burada ki hata cift tırnakla baslayıp tek tırnkla bitirmem.

print('gülsüm")
# yine aynı mantık hangi tırnak ile baslıyosam onunla bitirmeliyim.

print('I'm happy to learn!')
# hatanın sebebi 1. tırnak açılıs tırnağı sonraki kesme işaretini kapanıs tırnağı algılıyo.

print("I'm happy to learn!")  # hangi tırnakla baslıyosam içerde farklı bir tırnak kullanmalıyım.kesme işareti artık burada karakter görevinde.

print('I\'m Gülsüm.')  # escape karakter gelince önündeki ifadenin görevini sonlandırır ve böylece hata vermez.

print(''' Hey bakın" buraya" Gülsüm'ün yüzü gülüyor''')  # 3 tek tırnak içinde hem tek hem cift tırnak.

print("""
ben
ne güzel
öğreniyorum.
""")  # 3 tırnakla yazaonca metni nasıl yazarsam o sekilde cıktı alırım.

print("ben")
print("python")
print("öğreniyorum")  # bu da altalta cıktı vericek

print("3.14")
print(3.14)
print(type("3.14"))  # str
print(type(3.14))  # float

print("3.14"*3)  # 3.143.143.14
print(3.14 * 3)  # 9.42

print("gülsüm")
print()   # bir tane boşluk oluşturur.
print("eşgi")

print()
print("")  # ikiside boşluk verir.

print()
print('''')
  # 2. de bosluk olamaz hata verir. cünkü ilk 3 tırbağı okur o zaman da kapanıs tırnağı yok.

print('gülsüm\'ün kalemi')  # escape karakter \ den dolayı hata vermedi. \ kimin önüne gelirse onun  görevini sonlandırır.

print("gülsüm'ün yaptığı \"projeler\" bir atese attı beni.")

print("gülsüm yazııyyooorrr \t\t\thabire yazıyor")  # \t bosluk bırakıyor

print("gülsüm \nyazııyyooorrr\nhabire yazıyor")  # bir alt satıra gider.

